### ISSUE TITLE
support ===

### ISSUE THREAD

**Issue by afeld** [afeld/compare_by#1]
Thanks @dogweather for pointing out this is missing!

http://ruby-doc.org/core-2.3.0/Object.html#method-i-3D-3D-3D

**Comment by aaackerman** [comment]
After working on an implementation, I came to the conclusion that `===` does not appear to make sense as an addition to this gem. In classes, `===` is used as syntactic sugar for an `is_a?` behavior in case statements. This [stackoverflow question](https://stackoverflow.com/questions/3422223/vs-in-ruby) has a good explanation of the expected behavior. 

Usage

```
Integer === 2
=> true

Integer === "Hello, world"
=> false
```

I implemented a solution that would effectively do...

```
class SomeClass
  include CompareBy
  attr_accessor :some_attr, :some_other_attr
  compare_by :some_attr
end

s1 = SomeClass.new
s2.some_attr = String
s2 = SomeClass.new
s.some_attr = "Hello"
s3 = SomeClass.new
s3.some_attr = 5

s1 === s2
=> true (because s2's some_attr is a string)

s1 === s3
=> false (because s3's some_attr is an Integer)
```

Learned a lot about `===` here, would love to know why @dogweather suggested the addition!

**Comment by afeld** [comment]
Awesome, thanks for doing so much work looking into it, even though it turned out to be a [`wontfix`](http://www.urbandictionary.com/define.php?term=wontfix). @dogweather, let us know if you disagree!

**Comment by dogweather** [comment]
I agree that this is best left out of the lib. Especially since by default `===` seems to delegate to `==` or `eql?`. 

I initially suggested this because I naively thought that redefining it is part of the ruby object protocol. But, not so much.
